# Generated by Django 2.1 on 2020-02-23 04:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200223_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='racks',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webapp.Students'),
            preserve_default=False,
        ),
    ]
